apiVersion: v1
kind: Namespace
metadata:
  name: team-a
  labels:
    app.kubernetes.io/managed-by: flux
    team: team-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-b
  labels:
    app.kubernetes.io/managed-by: flux
    team: team-b
